# Diabetes training dataset from keggle

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_diabetes= pd.read_csv('diabetes.csv')

In [3]:
df_diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df_diabetes.duplicated().sum()

0

In [5]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [7]:
df_diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
df_diabetes['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [10]:
((df_diabetes['Outcome'].value_counts(normalize=True))*100).round(3)

Outcome
0    65.104
1    34.896
Name: proportion, dtype: float64

In [11]:
df_diabetes.corr()['Outcome'].sort_values(ascending=False)

Outcome                     1.000000
Glucose                     0.466581
BMI                         0.292695
Age                         0.238356
Pregnancies                 0.221898
DiabetesPedigreeFunction    0.173844
Insulin                     0.130548
SkinThickness               0.074752
BloodPressure               0.065068
Name: Outcome, dtype: float64

In [26]:
(df_diabetes==0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [12]:
df_diabetes[['Glucose', 'BloodPressure', 
                    'BMI', 'Insulin', 
                    'SkinThickness']].describe()

          Glucose  BloodPressure         BMI     Insulin  SkinThickness
count  768.000000     768.000000  768.000000  768.000000     768.000000
mean   120.894531      69.105469   31.992578   79.799479      20.536458
std     31.972618      19.355807    7.884160  115.244002      15.952218
min      0.000000       0.000000    0.000000    0.000000       0.000000
25%     99.000000      62.000000   27.300000    0.000000       0.000000
50%    117.000000      72.000000   32.000000   30.500000      23.000000
75%    140.250000      80.000000   36.600000  127.250000      32.000000
max    199.000000     122.000000   67.100000  846.000000      99.000000

In [14]:
'df_diabetes.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [16]:
(df_diabetes[['Glucose','BloodPressure','BMI','Insulin','SkinThickness']]==0).sum()

Glucose            5
BloodPressure     35
BMI               11
Insulin          374
SkinThickness    227
dtype: int64

In [17]:
print(df_diabetes.groupby(
    df_diabetes['Insulin'] == 0)['Outcome'].mean())

Insulin
False    0.329949
True     0.368984
Name: Outcome, dtype: float64

In [44]:
df_diabetes_clean = df_diabetes.copy()
df_diabetes_clean.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [45]:
df_diabetes_clean['Insulin_Missing'] = (df_diabetes_clean['Insulin']==0).astype(int)

In [46]:
df_diabetes_clean.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Insulin_Missing
0,6,148,72,35,0,33.6,0.627,50,1,1
1,1,85,66,29,0,26.6,0.351,31,0,1
2,8,183,64,0,0,23.3,0.672,32,1,1
3,1,89,66,23,94,28.1,0.167,21,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0

In [47]:
df_diabetes_clean['SkinThickness_Missing']= (df_diabetes_clean['SkinThickness']==0).astype(int)
df_diabetes_clean.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Insulin_Missing,SkinThickness_Missing
0,6,148,72,35,0,33.6,0.627,50,1,1,0
1,1,85,66,29,0,26.6,0.351,31,0,1,0
2,8,183,64,0,0,23.3,0.672,32,1,1,1
3,1,89,66,23,94,28.1,0.167,21,0,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0,0

In [48]:
cols = ['Glucose','BloodPressure','BMI','Insulin','SkinThickness']

In [49]:
df_diabetes_clean[cols] = df_diabetes_clean[cols].replace(0, np.nan)

In [50]:
df_diabetes_clean.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Insulin_Missing,SkinThickness_Missing
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1,1,0
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0,1,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1,1,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0,0,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1,0,0

In [51]:
for col in cols:
    df_diabetes_clean[col].fillna(df_diabetes_clean[col].median(), inplace=True)

In [52]:
df_diabetes_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    float64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    float64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
 9   Insulin_Missing           768 non-null    int32
 10  SkinThickness_Missing     768 non-null    int32
dtypes: float64(6), int32(2), int64(3)
memory usage: 60.1 KB

In [53]:
df_diabetes_clean.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Insulin_Missing,SkinThickness_Missing
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1,1,0
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0,1,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1,1,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0,0,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1,0,0

In [55]:
print(df_diabetes_clean.shape)

(768, 11)

In [56]:
print(df_diabetes_clean.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
Insulin_Missing             0
SkinThickness_Missing       0
dtype: int64

In [58]:
print(df_diabetes_clean.dtypes)

Pregnancies                   int64
Glucose                     float64
BloodPressure               float64
SkinThickness               float64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
Insulin_Missing               int32
SkinThickness_Missing         int32
dtype: object

In [59]:
(df_diabetes_clean==0).sum()

Pregnancies                 111
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                       0
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
Insulin_Missing             394
SkinThickness_Missing       541
dtype: int64

In [60]:
df_diabetes_clean['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [62]:
df_diabetes_clean.corr()['Outcome'].sort_values(ascending=False)

Outcome                     1.000000
Glucose                     0.492782
BMI                         0.312038
Age                         0.238356
Pregnancies                 0.221898
SkinThickness               0.214873
Insulin                     0.203790
DiabetesPedigreeFunction    0.173844
BloodPressure               0.165723
SkinThickness_Missing       0.052603
Insulin_Missing             0.040934
Name: Outcome, dtype: float64